/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.KhachHangDTO;

import static GUI.LoHang.formatter;
import java.awt.Color;

/**
 *
 * @author Locc
 */
public class KhachHang extends javax.swing.JPanel {

    private boolean isSelect;
    private KhachHangDTO khachHangDTO;

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
    }

    public KhachHang(KhachHangDTO khachHangDTO) {
        initComponents();
        this.khachHangDTO = new KhachHangDTO();
        this.khachHangDTO = khachHangDTO;
        jLabelMaKH.setText(khachHangDTO.getMaKHString());
        jLabelTenKH.setText(khachHangDTO.getTenKHString());
        jLabelSDT.setText(khachHangDTO.getSDTKHString());
        jLabelNgayDK.setText(formatter.format(khachHangDTO.getNgayDangKyDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaKH = new javax.swing.JLabel();
        jLabelTenKH = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelNgayDK = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(45, 96, 151)));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaKH.setText("Mã KH");
        jLabelMaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaKHMouseClicked(evt);
            }
        });
        add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        jLabelTenKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelTenKH.setText("Tên");
        jLabelTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTenKHMouseClicked(evt);
            }
        });
        add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 330, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSDT.setText("SDT");
        jLabelSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSDTMouseClicked(evt);
            }
        });
        add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 180, 60));

        jLabelNgayDK.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayDK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayDK.setText("NgayDK");
        jLabelNgayDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNgayDKMouseClicked(evt);
            }
        });
        add(jLabelNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 180, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        setBackground(new java.awt.Color(234, 105, 95));
        isSelect = true;
    }// GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        setBackground(Color.WHITE);
        isSelect = false;
    }// GEN-LAST:event_formFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        requestFocus();

    }// GEN-LAST:event_formMouseClicked

    private void jLabelMaKHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelMaKHMouseClicked
        // TODO add your handling code here:
        isSelect = true;
    }// GEN-LAST:event_jLabelMaKHMouseClicked

    private void jLabelTenKHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelTenKHMouseClicked
        // TODO add your handling code here:
        isSelect = true;
    }// GEN-LAST:event_jLabelTenKHMouseClicked

    private void jLabelSDTMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelSDTMouseClicked
        // TODO add your handling code here:
        isSelect = true;
    }// GEN-LAST:event_jLabelSDTMouseClicked

    private void jLabelNgayDKMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelNgayDKMouseClicked
        // TODO add your handling code here:
        isSelect = true;
    }// GEN-LAST:event_jLabelNgayDKMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelNgayDK;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenKH;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * @return the khachHangDTO
     */
    public KhachHangDTO getKhachHangDTO() {
        return khachHangDTO;
    }

    /**
     * @param khachHangDTO the khachHangDTO to set
     */
    public void setKhachHangDTO(KhachHangDTO khachHangDTO) {
        this.khachHangDTO = khachHangDTO;
    }
}
