/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.KhachHangDTO;

import static GUI.LoHang.formatter;

/**
 *
 * @author Locc
 */
public class KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
    }

    public KhachHang(KhachHangDTO khachHangDTO) {
        initComponents();
        jLabelMaKH.setText(khachHangDTO.getMaKHString().toString());
        jLabelTenKH.setText(khachHangDTO.getTenKHString());
        jLabelSDT.setText(khachHangDTO.getSDTKHString());
        jLabelNgayDK.setText(formatter.format(khachHangDTO.getNgayDangKyDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaKH = new javax.swing.JLabel();
        jLabelTenKH = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelNgayDK = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaKH.setText("Mã KH");
        add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 60));

        jLabelTenKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelTenKH.setText("Tên");
        add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 370, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSDT.setText("SDT");
        add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 180, 60));

        jLabelNgayDK.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayDK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayDK.setText("NgayDK");
        add(jLabelNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 180, 60));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelNgayDK;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenKH;
    // End of variables declaration//GEN-END:variables
}
