/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Locc
 */
public class LoHang extends javax.swing.JPanel {

    private String maLH;
    private String ngayNhap;
    private Integer SLSP;

    /**
     * Creates new form LoHang
     */
    public LoHang() {
        initComponents();
    }

    public LoHang(String maLH, String ngayNhap, Integer SLSP) {
        initComponents();
        this.maLH = maLH;
        this.ngayNhap = ngayNhap;
        this.SLSP = SLSP;

        jLabelMaLH.setText(maLH);
        jLabelNgayNhap.setText(ngayNhap);
        jLabelSLSP.setText(SLSP.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaLH = new javax.swing.JLabel();
        jLabelNgayNhap = new javax.swing.JLabel();
        jLabelSLSP = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 60));
        setMinimumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaLH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaLH.setText("Mã LH");
        add(jLabelMaLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 60));

        jLabelNgayNhap.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayNhap.setText("Ngày nhập");
        add(jLabelNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 170, 60));

        jLabelSLSP.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSLSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSLSP.setText("SL SP trong LH");
        add(jLabelSLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 190, 60));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMaLH;
    private javax.swing.JLabel jLabelNgayNhap;
    private javax.swing.JLabel jLabelSLSP;
    // End of variables declaration//GEN-END:variables
}
