/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import static java.lang.Integer.*;

/**
 *
 * @author Locc
 */
public class Product extends javax.swing.JPanel {

    private String ten;
    private String gia;
    private Integer sl;

    private boolean isSelect;

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    public Product(String ten, String gia) {
        initComponents();
        this.ten = ten;
        this.gia = gia;
        this.sl = 1;

        jLabelTenSP.setText(ten);
        jLabelSoLuong.setText(sl.toString());
        Integer tt = valueOf(gia) * sl;
        jLabelThanhTien.setText(tt.toString());
    }

    public void tangSoLuong() {
        sl++;
        jLabelSoLuong.setText(sl.toString());
    }

    public void giamSoLuong() {
        sl--;
        jLabelSoLuong.setText(sl.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenSP = new javax.swing.JLabel();
        jLabelSoLuong = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(479, 60));
        setMinimumSize(new java.awt.Dimension(479, 60));
        setPreferredSize(new java.awt.Dimension(479, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTenSP.setText("Tên");
        add(jLabelTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, -1));

        jLabelSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSoLuong.setText("Số lượng:");
        add(jLabelSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabelThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelThanhTien.setText("Tiền");
        add(jLabelThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenSP;
    private javax.swing.JLabel jLabelThanhTien;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the ten
     */
    public String getTen() {
        return ten;
    }

    /**
     * @param ten the ten to set
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * @return the gia
     */
    public String getGia() {
        return gia;
    }

    /**
     * @param gia the gia to set
     */
    public void setGia(String gia) {
        this.gia = gia;
    }

    /**
     * @return the sl
     */
    public Integer getSl() {
        return sl;
    }

    /**
     * @param sl the sl to set
     */
    public void setSl(Integer sl) {
        this.sl = sl;
    }

    /**
     * @return the jLabelSoLuong
     */
    public javax.swing.JLabel getjLabelSoLuong() {
        return jLabelSoLuong;
    }

    /**
     * @param jLabelSoLuong the jLabelSoLuong to set
     */
    public void setjLabelSoLuong(javax.swing.JLabel jLabelSoLuong) {
        this.jLabelSoLuong = jLabelSoLuong;
    }

    /**
     * @return the jLabelTenSP
     */
    public javax.swing.JLabel getjLabelTenSP() {
        return jLabelTenSP;
    }

    /**
     * @param jLabelTenSP the jLabelTenSP to set
     */
    public void setjLabelTenSP(javax.swing.JLabel jLabelTenSP) {
        this.jLabelTenSP = jLabelTenSP;
    }

    /**
     * @return the jLabelThanhTien
     */
    public javax.swing.JLabel getjLabelThanhTien() {
        return jLabelThanhTien;
    }

    /**
     * @param jLabelThanhTien the jLabelThanhTien to set
     */
    public void setjLabelThanhTien(javax.swing.JLabel jLabelThanhTien) {
        this.jLabelThanhTien = jLabelThanhTien;
    }

    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }
}
