/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Locc
 */
public class Product_icon extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public Product_icon() {
        initComponents();
    }

    public Product_icon(String ten, String gia, String sl) {
        initComponents();
        jLabelTen.setText(ten);
        jLabelGia.setText(gia);
        jLabelSL.setText(sl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTen = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelSL = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(160, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("icon");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jLabelTen.setText("Tên ");
        jPanel11.add(jLabelTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 25));

        jLabelGia.setText("Giá");
        jPanel11.add(jLabelGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 150, 25));

        jLabelSL.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSL.setText("SL");
        jPanel11.add(jLabelSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 25));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelSL;
    private javax.swing.JLabel jLabelTen;
    private javax.swing.JPanel jPanel11;
    // End of variables declaration//GEN-END:variables
}
