/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Locc
 */
public class Product_icon extends javax.swing.JPanel implements MouseListener {

    private String ten;
    private String gia;
    private String sl;

    /**
     * Creates new form Product
     */
    public Product_icon() {
        initComponents();
        addMouseListener(this);
    }

    public Product_icon(String ten, String gia, String sl) {
        initComponents();
        this.ten = ten;
        this.gia = gia;
        this.sl = sl;
        jLabelTen.setText(ten);
        jLabelGia.setText(gia);
        jLabelSL.setText(sl);
        addMouseListener(this);

        jLabelIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Xử lý sự kiện khi JLabel được nhấp chuột
                System.out.println("Label clicked!");
            }
        });
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        // Xử lý hành động khi panel được click
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelTen = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelSL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(250, 376));
        setMinimumSize(new java.awt.Dimension(250, 376));
        setPreferredSize(new java.awt.Dimension(250, 376));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(230, 315));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcon.setText("icon");
        jLabelIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 210, 210));

        jLabelTen.setFont(new java.awt.Font("Be Vietnam Pro ExtraLight", 0, 20)); // NOI18N
        jLabelTen.setText("Tên ");
        jPanel11.add(jLabelTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 25));

        jLabelGia.setFont(new java.awt.Font("Be Vietnam Pro ExtraLight", 0, 20)); // NOI18N
        jLabelGia.setText("Giá");
        jPanel11.add(jLabelGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 25));

        jLabelSL.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSL.setFont(new java.awt.Font("Be Vietnam Pro ExtraLight", 0, 20)); // NOI18N
        jLabelSL.setText("SL");
        jPanel11.add(jLabelSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, 25));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 326));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelSL;
    private javax.swing.JLabel jLabelTen;
    private javax.swing.JPanel jPanel11;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ten
     */
    public String getTen() {
        return ten;
    }

    /**
     * @param ten the ten to set
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * @return the gia
     */
    public String getGia() {
        return gia;
    }

    /**
     * @param gia the gia to set
     */
    public void setGia(String gia) {
        this.gia = gia;
    }

    /**
     * @return the sl
     */
    public String getSl() {
        return sl;
    }

    /**
     * @param sl the sl to set
     */
    public void setSl(String sl) {
        this.sl = sl;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabelIcon() {
        return jLabelIcon;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabelIcon(javax.swing.JLabel jLabel4) {
        this.jLabelIcon = jLabel4;
    }

    /**
     * @return the jLabelGia
     */
    public javax.swing.JLabel getjLabelGia() {
        return jLabelGia;
    }

    /**
     * @param jLabelGia the jLabelGia to set
     */
    public void setjLabelGia(javax.swing.JLabel jLabelGia) {
        this.jLabelGia = jLabelGia;
    }

    /**
     * @return the jLabelSL
     */
    public javax.swing.JLabel getjLabelSL() {
        return jLabelSL;
    }

    /**
     * @param jLabelSL the jLabelSL to set
     */
    public void setjLabelSL(javax.swing.JLabel jLabelSL) {
        this.jLabelSL = jLabelSL;
    }

    /**
     * @return the jLabelTen
     */
    public javax.swing.JLabel getjLabelTen() {
        return jLabelTen;
    }

    /**
     * @param jLabelTen the jLabelTen to set
     */
    public void setjLabelTen(javax.swing.JLabel jLabelTen) {
        this.jLabelTen = jLabelTen;
    }

    /**
     * @return the jPanel11
     */
    public javax.swing.JPanel getjPanel11() {
        return jPanel11;
    }

    /**
     * @param jPanel11 the jPanel11 to set
     */
    public void setjPanel11(javax.swing.JPanel jPanel11) {
        this.jPanel11 = jPanel11;
    }
}
