/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Admin;

import DTO.NhanVienDTO;

/**
 *
 * @author Locc
 */
public class NhanVien extends javax.swing.JPanel {

    private NhanVienDTO nhanVienDTO;

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();
    }

    public NhanVien(NhanVienDTO nhanVienDTO) {
        initComponents();

        this.nhanVienDTO = new NhanVienDTO();
        this.nhanVienDTO = nhanVienDTO;

        jLabelLuong.setText(nhanVienDTO.getLuongInteger().toString());
        jLabelMaNV.setText(nhanVienDTO.getMaNVString());
        jLabelSDT.setText(nhanVienDTO.getSDTNVString());
        jLabelTenNV.setText(nhanVienDTO.getHoTenNVString());
        jLabelChucVu.setText(nhanVienDTO.getChucVuNVString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaNV = new javax.swing.JLabel();
        jLabelTenNV = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelLuong = new javax.swing.JLabel();
        jLabelChucVu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(45, 96, 151)));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setMinimumSize(new java.awt.Dimension(1200, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaNV.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaNV.setText("NV000001");
        add(jLabelMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 60));

        jLabelTenNV.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelTenNV.setText("Tên");
        add(jLabelTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 280, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSDT.setText("SDT");
        add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 170, 60));

        jLabelLuong.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelLuong.setText("Lương");
        add(jLabelLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 170, 60));

        jLabelChucVu.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelChucVu.setText("Chức vụ");
        add(jLabelChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 170, 60));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelChucVu;
    private javax.swing.JLabel jLabelLuong;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenNV;
    // End of variables declaration//GEN-END:variables
}
