/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Admin;

import BUS.NhanVienBUS;
import DAO_Hibernate.NhanVienDAO;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Locc
 */
public class QLNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QLNhanVien
     */
    public QLNhanVien() {
        initComponents();
        jDialogDeleteSP.setLocationRelativeTo(null);
        NhanVienBUS nhanVienBUS = new NhanVienBUS();
        for (int i = 0; i < nhanVienBUS.getListnNhanVienDTOs().size(); i++) {
            NhanVien nhanVien = new NhanVien(nhanVienBUS.getListnNhanVienDTOs().get(i));
            jPanel4.add(nhanVien);
        }
        jPanel4.revalidate();
        jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDeleteSP = new javax.swing.JDialog();
        panelRound2 = new GUI.PanelRound();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jTextField5 = new javax.swing.JTextField();
        jPanelDel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTenNV = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelChucVu = new javax.swing.JLabel();
        jLabelMaNV = new javax.swing.JLabel();
        jLabelLuong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        jDialogDeleteSP.setFocusable(false);
        jDialogDeleteSP.setFocusableWindowState(false);
        jDialogDeleteSP.setModal(true);
        jDialogDeleteSP.setUndecorated(true);
        jDialogDeleteSP.setResizable(false);
        jDialogDeleteSP.setSize(new java.awt.Dimension(625, 210));
        jDialogDeleteSP.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(143, 203, 253));
        panelRound2.setMaximumSize(new java.awt.Dimension(625, 210));
        panelRound2.setMinimumSize(new java.awt.Dimension(625, 210));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 22)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Xác nhận xóa sản phẩm đã chọn?");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 30, 610, -1));

        jLabel20.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 115, 130));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Lưu ý sản phẩm sẽ bị xoá hoàn toàn và không thể khôi phục");
        panelRound2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 610, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 96, 151), 2));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.setFocusable(false);
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 96, 151));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Hủy bỏ");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 5, 104, 32));

        panelRound2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 143, 170, 45));

        jLabel22.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 19)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Xác nhận");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setFocusable(false);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        panelRound2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 104, 32));

        jDialogDeleteSP.getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 625, 210));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(143, 203, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(143, 203, 253));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search 1.png"))); // NOI18N
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 48, 48));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setMaximumSize(new java.awt.Dimension(330, 50));
        panelRound1.setMinimumSize(new java.awt.Dimension(330, 50));
        panelRound1.setPreferredSize(new java.awt.Dimension(330, 50));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setFont(new java.awt.Font("Be Vietnam Pro", 0, 24)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panelRound1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 280, 50));

        jPanel16.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 50));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 430, 90));

        jPanelDel.setBackground(new java.awt.Color(45, 96, 151));
        jPanelDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDelMouseClicked(evt);
            }
        });
        jPanelDel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Xóa NV");
        jPanelDel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        jPanel1.add(jPanelDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 10, 230, 70));

        jPanel6.setBackground(new java.awt.Color(45, 96, 151));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thêm NV");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 70));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 10, 230, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPanel2.setBackground(new java.awt.Color(45, 96, 151));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenNV.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelTenNV.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenNV.setText("Tên");
        jPanel2.add(jLabelTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 280, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelSDT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSDT.setText("SDT");
        jPanel2.add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 170, 60));

        jLabelChucVu.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChucVu.setText("Chức vụ");
        jPanel2.add(jLabelChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 170, 60));

        jLabelMaNV.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMaNV.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelMaNV.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaNV.setText("Mã NV");
        jPanel2.add(jLabelMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 60));

        jLabelLuong.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelLuong.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLuong.setText("Lương");
        jPanel2.add(jLabelLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 170, 60));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel4);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
//        String keyword = jTextField5.getText();
//        TestProcedure testProcedure = new TestProcedure();
//        jPanel4.removeAll();
//        if (keyword.length() != 0) {
//            List<KhachHangDTO> khachHangDTOs = testProcedure.SEARCH_KHACHHANG(keyword);
//            if (!khachHangDTOs.isEmpty()) {
//                for (KhachHangDTO khachHangDTO : khachHangDTOs) {
//                    //                    Product_icon product_icon = new Product_icon(sanPhamDTO);
//                    KhachHang khachHang = new KhachHang(khachHangDTO);
//                    jPanel4.add(khachHang);
//                }
//            }
//        } else {
//            for (int i = 0; i < khachHangBUS.getlist_KhachHangDTOs().size(); i++) {
//                KhachHang khachHang = new KhachHang(khachHangBUS.getlist_KhachHangDTOs().get(i));
//                jPanel4.add(khachHang);
//            }
//        }
//        jPanel4.revalidate();
//        jPanel4.repaint();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jPanelDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDelMouseClicked
        // TODO add your handling code here:
//        jDialogDeleteKH.setVisible(true);
        Component[] components = jPanel4.getComponents();

        // Iterate over the components in reverse order
        for (int i = components.length - 1; i >= 0; i--) {
            Component component = components[i];

            // Check if the component is an instance of Product
            if (component instanceof NhanVien) {
                NhanVien nhanVien = (NhanVien) component;

                // Check if the product needs to be deleted
                if (nhanVien.isSelect()) {
                    jDialogDeleteSP.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jPanelDelMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
//        khachHangDAO = new KhachHangDAO();
//        jTextFieldMaKH.setText(khachHangDAO.AutoGenerateMaKH());
//        AbstractDocument doc = (AbstractDocument) jTextFieldSDTKH.getDocument();
//        doc.setDocumentFilter(new LimitDigitsDocumentFilter(10));
//        jDialogAddKH.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        jDialogDeleteSP.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        Component[] components = jPanel4.getComponents();

        // Iterate over the components in reverse order
        for (int i = components.length - 1; i >= 0; i--) {
            Component component = components[i];

            // Check if the component is an instance of Product
            if (component instanceof NhanVien) {
                NhanVien nhanVien = (NhanVien) component;

                // Check if the product needs to be deleted
                if (nhanVien.isSelect()) {
                    // Remove the Nhan vien from Database
                    NhanVienDAO nhanVienDAO = new NhanVienDAO();
                    try {
                        nhanVienDAO.deleteNhanVien(nhanVien.getNhanVienDTO().getMaNVString());
                    } catch (SQLException e) {
                        // Xử lý SQLException
                        JOptionPane.showMessageDialog(null, "Lỗi SQL: " + e.getMessage());

                    } catch (Exception e) {
                        // Xử lý các exception khác
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Lỗi: " + e.getMessage());
                    } finally {
                        jDialogDeleteSP.dispose();
                        jPanel4.removeAll();
                        NhanVienBUS nhanVienBUS = new NhanVienBUS();
                        for (int j = 0; j < nhanVienBUS.getListnNhanVienDTOs().size(); j++) {
                            NhanVien nhanVien1 = new NhanVien(nhanVienBUS.getListnNhanVienDTOs().get(j));
                            jPanel4.add(nhanVien1);
                        }
                        jPanel4.revalidate();
                        jPanel4.repaint();
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogDeleteSP;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelChucVu;
    private javax.swing.JLabel jLabelLuong;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenNV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
